-- ASARVO — powiadomienia e-mail o spadku ceny (Brevo)
-- Uruchom TEN PLIK w Supabase -> SQL Editor -> Run.

alter table public.profiles
  add column if not exists email_price_alerts_enabled boolean not null default false;

alter table public.price_watches
  add column if not exists email_alert_armed boolean not null default true;

alter table public.price_watches
  add column if not exists last_email_notified_at timestamptz;

alter table public.price_watches
  add column if not exists last_email_notified_price numeric(12,2);

alter table public.price_watches
  add column if not exists last_email_notified_target_price numeric(12,2);

create table if not exists public.price_email_notifications (
  id bigint generated by default as identity primary key,
  price_watch_id uuid not null references public.price_watches(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  recipient text not null,
  price numeric(12,2) not null,
  target_price numeric(12,2) not null,
  provider text not null default 'brevo',
  provider_message_id text,
  status text not null default 'sent',
  created_at timestamptz not null default now()
);

alter table public.price_email_notifications enable row level security;

drop policy if exists "Users can read own price email notifications"
  on public.price_email_notifications;

create policy "Users can read own price email notifications"
  on public.price_email_notifications
  for select
  using (auth.uid() = user_id);

create index if not exists price_email_notifications_user_created_idx
  on public.price_email_notifications(user_id, created_at desc);

create index if not exists price_email_notifications_watch_created_idx
  on public.price_email_notifications(price_watch_id, created_at desc);

-- Po zmianie progu cena ma dostać szansę na nowy alert.
-- Sam kod aplikacji ustawia email_alert_armed=true przy edycji progu.
